### ISSUE TITLE
Entries are shown multiple times

### ISSUE THREAD

**Issue by rickfeuerabend** [snowflakeproductionsgmbh/snowbabel#23] opened 2017-12-01 09:09 UTC
All entries are indexed or just displayed multiple times.

<img width="773" alt="multiple_items" src="https://user-images.githubusercontent.com/18306618/33475711-b5e0a124-d67f-11e7-98f1-a860c18f458d.png">

**Comment by AnuBN** [comment] 2017-12-01 09:18
Hello mate,
Can you please make sure that same language labels aren't repeatedly used in several language files?
Because from your screenshot, same language labels with different values are clear. Can you please check again? Feedbacks are welcomed. :+1:

**Comment by rickfeuerabend** [comment] 2017-12-12 12:44
Hi sorry for late answer, I checked and in the lables are only used once. 
At the moment I have like four entries by one label. Couldn't figure out the reason. 
I also checked the database and also there every label has only single record.

![staubli___development____typo3_cms_8_7_8_](https://user-images.githubusercontent.com/18306618/33885093-8458ba58-df42-11e7-970d-00c9d1129ddf.png)

Do you have any idea?

**Comment by AnuBN** [comment] 2018-01-04 06:30
Hello @rickfeuerabend 
We reproduced this issue only by duplicating our language files. I hope you really understood what I've been trying to say.
You don't have to check tables for label usage. Inside the extension directory please make sure, every language file use a single label exactly once.
If it is of no help, you can share your available language files. Our team will track the situation. 
Thank you. Good Day.

**Comment by WebsiteDeveloper** [comment] 2018-08-30 01:33
@rickfeuerabend Any more info on this?
Otherwise i will close this.

**Closed as completed** 2018-10-08 16:04 UTC
Labels: question
